version: '3'

services:
  web:
    build: ./web
    command: gunicorn main:app -w 1 -b :5000 --reload -t 600
    ports:
      - 5001:5000
    volumes:
      - ./web:/home/app/web
    depends_on:
      - redis
    env_file:
      - .env.development
  redis:
    image: redis:alpine
    ports:
      - 6379:6379